@startmindmap mindmap

title リモートアクセスセキュリティ再精査

*[#Orange] リモートアクセスの\nセキュリティリスク
**[#Orange] 端末紛失による情報漏洩（第3者攻撃）
***[#Orange] パスワード攻撃による不正ログイン
****_ リモートロック・リモートワイプ
*****_ MDM（モバイルデバイス管理）
****_ 多要素認証

***[#Orange] HDDの差し替えによる情報抜出
****_ HDD暗号化
*****_ bitlocker
****_ 端末にデータを保存させない
*****_ MAM（モバイルアプリケーション管理）

**[#Orange] 端末から業務システムを経由した情報漏洩
***[#Orange] 当事者攻撃
****[#Orange]  可搬媒体による\nデータの不正持ち出し
*****_ 端末にデータを保存させない
******_ MAM（モバイルアプリケーション管理）
*****_ 端末に可搬媒体を認識させない
******_ MDM（モバイルデバイス管理）
****[#Orange]  画面撮影
***[#Orange] 第3者攻撃
****[#Orange] 画面の盗み見
*****_ カメラによる常時本人監視
****[#Orange] キーロガー
*****_ アプリケーションのインストール制限
******_ MAM（モバイルアプリケーション管理）

**[#Orange] SNSなどネット利用による情報漏洩（当事者攻撃）
***[#Orange] サイトへのアップロード
****_ ホワイトリストによるインターネットアクセス制限
*****_ proxy制限
***[#Orange] メール送信
****_ ホワイトリストによるメール利用制限
*****_ 送信先IP・ポート制限

**[#Orange] 社外NWからのアクセスリスク（第3者攻撃）

***[#Orange] 端末のウィルス感染からの社内感染拡大
****_ 端末OSの常時セキュリティパッチ
*****_ MDM（モバイルデバイス管理）
****_ VDIによるネットワークの分離
*****_ VID Gateway
***[#Orange] 盗聴・改ざん
****_ VPN
****_ VDI＋SSL
*****[#Orange] 不正VDIクライアント利用による盗聴
******_ MAM（モバイルアプリケーション管理）



@endmindmap