name: Mirror to S3

on:
  push:
    branches:
    - master # ミラーリングするブランチ

permissions:
  id-token: write # OIDCトークンの発行を許可
  contents: read # リポジトリ内容の読み取りを許可

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # リポジトリの内容を取得

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::030245512612:role/github-actions-s3
        aws-region: ap-northeast-1 # 使用するAWSリージョン

    - name: Extract repository name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Sync to S3
      env:
        REPOSITORY_NAME: ${{ github.repository }}
      run: | # htmlファイルのみをS3に同期
        aws s3 sync ./ s3://recrue4-docs/cf/$REPO_NAME/ \
          --exclude "*" \
          --include "*.html" \
          --delete